[project]
name = "kafka-consumer"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "confluent-kafka==2.3.0",
    "pandas>=2.3.3",
    "pyyaml==6.0.1",
    "requests>=2.32.5",
]
